spring:
  profiles: 
    active: dev
---
spring:
  profiles: dev
  application:
    name: consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    
server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka

feign:
  hystrix:
    enabled: true
---
spring:
  profiles: test
  application:
    name: consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    
server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka

feign:
  hystrix:
    enabled: true
