server:
  port: 80

spring:
  application:
    name: consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka

feign:
  hystrix:
    enabled: true
---
server:
  port: 8082

spring:
  application:
    name: zuul-application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: provider
